# Generated by Django 5.2.8 on 2025-12-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('farmacos', 'Fármacos'), ('bebidas', 'Bebidas'), ('lacteos', 'Lácteos'), ('carnes_pescados', 'Carnes y Pescados'), ('frutas_verduras', 'Frutas y Verduras'), ('limpieza', 'Limpieza'), ('snacks', 'Snacks'), ('otros', 'Otros')], default='Otros', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
