# Generated by Django 5.2.8 on 2025-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('farmacos', 'Fármacos'), ('bebidas', 'Bebidas'), ('lacteos', 'Lácteos'), ('carnes_pescados', 'Carnes y Pescados'), ('frutas_verduras', 'Frutas y Verduras'), ('limpieza', 'Limpieza'), ('snacks', 'Snacks'), ('otros', 'Otros')], default='Otros', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
